version: '{build}'

environment:
  PYTHON: "C:\\Python27-x64"
  NINJA_URL: "https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip"
  CMAKE_URL: "https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-win64-x64.zip"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      GENERATOR: Visual Studio 15 2017

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      GENERATOR: Visual Studio 15 2017 Win64

install:
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\tools\cmake > nul
  - set PATH=C:\projects\tools\cmake\bin;%PATH%
  - cmake --version
  - if "%COMPILER%"=="mingw" appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - if "%COMPILER%"=="mingw" 7z x ninja.zip -oC:\projects\tools\ninja > nul
  - if "%COMPILER%"=="mingw" set PATH=C:\projects\tools\ninja;%PATH%
  - if "%COMPILER%"=="mingw" set PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%PATH%
  - if "%COMPILER%"=="mingw" g++ --version

init:
  - msbuild /version

before_build:
  - cmake . -G "%GENERATOR%" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"

build_script:
  - cmake --build . --config Release

test_script:
  - ctest -C Release -V -j
